extends Node
var change_on_enter_x=100
var change_on_up_mouse_wheel=10;
var width_of_logo_of_card=90
var width_of_card=180
var height_of_card=1003
func get_change_on_enter_mouse():
	return change_on_enter_x
func get_change_on_up_mouse_wheel():
	return change_on_up_mouse_wheel
func get_logo_width():
	return width_of_logo_of_card
func get_width_of_card():
	return width_of_card
func get_height_of_card():
	return height_of_card
