extends Node
var change_on_enter_x:=100.0
var change_on_up_mouse_wheel:=10.0
var width_of_logo_of_card:=90.0
var width_of_card:=180.0
var height_of_card:=1003.0
func get_change_on_enter_mouse()->float:
	return change_on_enter_x
func get_change_on_up_mouse_wheel():
	return change_on_up_mouse_wheel
func get_logo_width()->float:
	return width_of_logo_of_card
func get_width_of_card()->float:
	return width_of_card
func get_height_of_card()->float:
	return height_of_card
